# Generated by Django 4.0.6 on 2022-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('code_expired_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=32)),
                ('lifetime_end', models.DateTimeField()),
                ('email', models.EmailField(max_length=25)),
            ],
            options={
                'verbose_name': 'Email confirmation',
                'verbose_name_plural': 'Email confirmations',
            },
        ),
        migrations.CreateModel(
            name='SMSConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('code_expired_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=32)),
                ('lifetime_end', models.DateTimeField()),
                ('phone', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'SMS confirmation',
                'verbose_name_plural': 'SMS confirmations',
            },
        ),
    ]
