# Generated by Django 4.2.5 on 2023-09-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_userlesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="learning.lesson",
                verbose_name="Lesson",
            ),
        ),
    ]
