# Generated by Django 4.2.5 on 2023-09-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0003_alter_test_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="locked",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "correct_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Correct Count"
                    ),
                ),
                (
                    "wrong_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Wrong Count"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="learning.test",
                        verbose_name="Test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Test",
                "verbose_name_plural": "User Tests",
            },
        ),
    ]
