# Generated by Django 4.2.5 on 2023-09-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_usertest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.test",
                verbose_name="Test",
            ),
        ),
    ]
