# Generated by Django 4.2.5 on 2023-10-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_useranswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
            },
        ),
    ]
