# Generated by Django 4.2.5 on 2023-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_alter_test_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntranceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "correct_option",
                    models.CharField(max_length=255, verbose_name="Correct Option"),
                ),
                (
                    "wrong_option",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Wrong Option",
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Entrance Question",
                "verbose_name_plural": "Entrance Questions",
                "ordering": ["order"],
            },
        ),
    ]
