# Generated by Django 4.2.5 on 2023-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_entrancequestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlesson",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="closed",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="status",
            field=models.CharField(
                choices=[
                    ("locked", "Locked"),
                    ("closed", "Closed"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="locked",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
