# Generated by Django 5.0 on 2023-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_alter_usertest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="audio", verbose_name="Audio"
            ),
        ),
    ]
