# Generated by Django 5.0 on 2023-12-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_question_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.IntegerField(verbose_name="Order"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("language", "order")},
        ),
    ]
