# Generated by Django 5.0 on 2023-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0013_entrancequestion_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Subtitle"
            ),
        ),
    ]
