# Generated by Django 4.2.5 on 2023-10-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_subscribe_from_user_subscribe_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscribe_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscribe_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
