# Generated by Django 4.2.5 on 2023-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_subscribe_from_alter_user_subscribe_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
